#!/usr/bin/env python3
"""Build the Autodesk API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Reality Capture': 'Reality Cap.',
    'Sustainability': 'Sustainability',
    'Data Connector': 'Data Connector',
    'Model Coordination': 'Model Coord.',
    'Model Properties': 'Model Props',
}

LINES = [
    {
        "name": 'Platform Services',
        "color": '#0696D7',
        "stations": [
        ('Authentication', (270, 195)),
        ('Data Management', (440, 175)),
        ('Model Derivative', (620, 165)),
        ('Design Automation', (810, 175)),
        ('Webhooks', (970, 200)),
        ],
    },
    {
        "name": 'AEC & Data',
        "color": '#0E9D6E',
        "stations": [
        ('AEC Data Model', (270, 320)),
        ('Data Exchange', (430, 295)),
        ('Reality Capture', (610, 295)),
        ('Tandem Data', (790, 295)),
        ('Sustainability', (960, 320)),
        ],
    },
    {
        "name": 'ACC — Project',
        "color": '#E68B1F',
        "stations": [
        ('Account Admin', (270, 440)),
        ('Issues', (430, 415)),
        ('RFIs', (590, 415)),
        ('Cost Mgmt', (760, 415)),
        ('Data Connector', (930, 440)),
        ],
    },
    {
        "name": 'ACC — Models',
        "color": '#7B3FE4',
        "stations": [
        ('Model Coordination', (270, 560)),
        ('Assets', (450, 535)),
        ('Locations', (610, 535)),
        ('Sheets', (770, 535)),
        ('Model Properties', (940, 560)),
        ],
    },
    {
        "name": 'ACC — Workflow',
        "color": '#1E5BD0',
        "stations": [
        ('Forms', (270, 680)),
        ('Submittals', (440, 655)),
        ('Reviews', (610, 655)),
        ('Transmittals', (780, 655)),
        ('Photos', (950, 680)),
        ],
    },
    {
        "name": 'ACC — Specialized',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Build Photos', (640, 770)),
        ('AutoSpecs', (760, 815)),
        ('Takeoff', (520, 815)),
        ('BIM 360', (640, 800)),
        ],
    },
]

URL_OVERRIDES = {
    'Authentication': 'https://apis.apis.io/apis/autodesk/authentication-api/',
    'Data Management': 'https://apis.apis.io/apis/autodesk/data-management-api/',
    'Model Derivative': 'https://apis.apis.io/apis/autodesk/model-derivative-api/',
    'Design Automation': 'https://apis.apis.io/apis/autodesk/design-automation-api/',
    'Webhooks': 'https://apis.apis.io/apis/autodesk/webhooks-api/',
    'AEC Data Model': 'https://apis.apis.io/apis/autodesk/aec-data-model-api/',
    'Data Exchange': 'https://apis.apis.io/apis/autodesk/data-exchange-api/',
    'Reality Capture': 'https://apis.apis.io/apis/autodesk/reality-capture-api/',
    'Tandem Data': 'https://apis.apis.io/apis/autodesk/tandem-data-api/',
    'Sustainability': 'https://apis.apis.io/apis/autodesk/sustainability-data-api/',
    'Account Admin': 'https://apis.apis.io/apis/autodesk/acc-account-admin-api/',
    'Issues': 'https://apis.apis.io/apis/autodesk/acc-issues-api/',
    'RFIs': 'https://apis.apis.io/apis/autodesk/acc-rfis-api/',
    'Cost Mgmt': 'https://apis.apis.io/apis/autodesk/acc-cost-management-api/',
    'Data Connector': 'https://apis.apis.io/apis/autodesk/acc-data-connector-api/',
    'Model Coordination': 'https://apis.apis.io/apis/autodesk/acc-model-coordination-api/',
    'Assets': 'https://apis.apis.io/apis/autodesk/acc-assets-api/',
    'Locations': 'https://apis.apis.io/apis/autodesk/acc-locations-api/',
    'Sheets': 'https://apis.apis.io/apis/autodesk/acc-sheets-api/',
    'Model Properties': 'https://apis.apis.io/apis/autodesk/acc-model-properties-api/',
    'Forms': 'https://apis.apis.io/apis/autodesk/acc-forms-api/',
    'Submittals': 'https://apis.apis.io/apis/autodesk/acc-submittals-api/',
    'Reviews': 'https://apis.apis.io/apis/autodesk/acc-reviews-api/',
    'Transmittals': 'https://apis.apis.io/apis/autodesk/acc-transmittals-api/',
    'Photos': 'https://apis.apis.io/apis/autodesk/acc-photos-api/',
    'Build Photos': 'https://apis.apis.io/apis/autodesk/autodesk-build-photos/',
    'AutoSpecs': 'https://apis.apis.io/apis/autodesk/acc-autospecs-api/',
    'Takeoff': 'https://apis.apis.io/apis/autodesk/acc-takeoff-api/',
    'BIM 360': 'https://apis.apis.io/apis/autodesk/bim-360-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Autodesk API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: autodesk/openapi · github.com/api-evangelist/autodesk',
        out_dir=Path(__file__).resolve().parent,
        out_basename='autodesk-subway-map',
        provider_id='autodesk',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
